### PR TITLE
Update README description

### PR DESCRIPTION
**Pull request by stoe**

### CODE REVIEW

**Comment by stoe** [comment]
@hectorsector can you check this and let me know if I can :ship:?

**Comment by hectorsector** [comment]
:+1:

**Comment by stoe** [comment]
👍

**Comment by gprasant** [comment]
👍

**Comment by stoe** [comment]
👎

**Comment by stoe** [comment]
👍

**Comment by stoe** [comment]
👍

**Comment by stoe** [comment]
:+1:

**Pull request closed without merging**
